-- Migration repeatable. Preserves existing agreements, users, tariffs and history.
begin;
do $$ begin
  create type public.app_role as enum ('administrador', 'comercial', 'consulta');
exception when duplicate_object then null; end $$;

create table if not exists public."Aliados" (
  "Id" bigint generated by default as identity primary key,
  "Compañia" text not null,
  "Actividad_comercial" text,
  "Producto" text,
  "Fecha_Gestion_comercial" date,
  "Responsable_cliente" text,
  "Telefono" text,
  email_cliente text,
  "Mes_renovacion" text,
  tarifa jsonb not null default '{}'::jsonb,
  actividades jsonb not null default '[]'::jsonb
);
alter table public."Aliados"
  add column if not exists created_by uuid references auth.users(id),
  add column if not exists updated_by uuid references auth.users(id),
  add column if not exists updated_at timestamptz default now(),
  add column if not exists archived_at timestamptz;
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '', email text not null,
  role public.app_role not null default 'consulta', is_active boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.audit_logs (
  id bigint generated always as identity primary key, user_id uuid,
  action text not null, entity text not null, entity_id text,
  old_data jsonb, new_data jsonb, created_at timestamptz not null default now()
);
create table if not exists public.alert_log (
  id bigint generated always as identity primary key, alert_key text unique not null,
  agreement_id bigint, alert_type text, scheduled_for date, days_before integer,
  run_slot text, sent_at timestamptz, recipient text
);
-- Existing rows were recorded as sent by the previous application.
alter table public.alert_log
  add column if not exists status text not null default 'sent',
  add column if not exists attempts integer not null default 0,
  add column if not exists last_error text,
  add column if not exists provider_id text,
  add column if not exists payload jsonb,
  add column if not exists claimed_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();
alter table public.alert_log alter column status set default 'pending';
alter table public.alert_log alter column sent_at drop default;
create index if not exists aliados_active_idx on public."Aliados"("Id") where archived_at is null;
create index if not exists audit_created_idx on public.audit_logs(created_at desc);
create index if not exists alert_retry_idx on public.alert_log(status, updated_at);

create or replace function public.my_role() returns public.app_role
language sql stable security definer set search_path = public
as $$ select role from public.profiles where id = auth.uid() and is_active $$;

create or replace function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public
as $$ begin
  insert into public.profiles(id, full_name, email)
  values(new.id, coalesce(new.raw_user_meta_data->>'full_name', ''), coalesce(new.email, ''))
  on conflict(id) do nothing;
  return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
insert into public.profiles(id, full_name, email)
select id, coalesce(raw_user_meta_data->>'full_name', ''), coalesce(email, '') from auth.users
on conflict(id) do nothing;

create or replace function public.audit_aliados() returns trigger
language plpgsql security definer set search_path = public
as $$ declare action_name text; item jsonb; begin
  if auth.uid() is not null and public.my_role() not in ('administrador','comercial') then
    raise exception 'No autorizado' using errcode = '42501';
  end if;
  if tg_op = 'INSERT' then
    if new.archived_at is not null and auth.uid() is not null and public.my_role() <> 'administrador' then
      raise exception 'Solo el administrador puede archivar' using errcode = '42501';
    end if;
    new.created_by := auth.uid(); new.updated_by := auth.uid(); new.updated_at := clock_timestamp();
    action_name := 'INSERT';
  else
    if new."Id" is distinct from old."Id" then raise exception 'El identificador no puede cambiar'; end if;
    if auth.uid() is not null and public.my_role() <> 'administrador' and
       (new.archived_at is distinct from old.archived_at or old.archived_at is not null) then
      raise exception 'Solo el administrador puede archivar o restaurar' using errcode = '42501';
    end if;
    new.created_by := old.created_by; new.updated_by := auth.uid(); new.updated_at := clock_timestamp();
    action_name := case when new.archived_at is distinct from old.archived_at then
      case when new.archived_at is null then 'RESTORE' else 'ARCHIVE' end else 'UPDATE' end;
  end if;
  if nullif(btrim(new."Compañia"), '') is null then raise exception 'La compañía es obligatoria'; end if;
  if new.tarifa is not null and jsonb_typeof(new.tarifa) <> 'object' then raise exception 'Tarifas inválidas'; end if;
  if new.actividades is not null and jsonb_typeof(new.actividades) <> 'array' then raise exception 'Seguimientos inválidos'; end if;
  for item in select value from jsonb_each(coalesce(new.tarifa, '{}'::jsonb)) loop
    if jsonb_typeof(item) <> 'number' or (item #>> '{}')::numeric < 0 then raise exception 'Las tarifas deben ser valores no negativos'; end if;
  end loop;
  insert into public.audit_logs(user_id, action, entity, entity_id, old_data, new_data)
  values(auth.uid(), action_name, 'Aliados', new."Id"::text, case when tg_op = 'UPDATE' then to_jsonb(old) else null end, to_jsonb(new));
  return new;
end $$;
drop trigger if exists trg_audit_aliados on public."Aliados";
create trigger trg_audit_aliados before insert or update on public."Aliados" for each row execute function public.audit_aliados();

create or replace function public.guard_profile_update() returns trigger
language plpgsql security definer set search_path = public
as $$ begin
  -- Serialize role changes so two administrators cannot remove the last access concurrently.
  perform pg_advisory_xact_lock(7192401);
  if new.id is distinct from old.id then raise exception 'El identificador no puede cambiar'; end if;
  if old.role = 'administrador' and old.is_active and (new.role <> 'administrador' or not new.is_active)
     and not exists(select 1 from public.profiles where id <> old.id and role = 'administrador' and is_active) then
    raise exception 'No puedes bloquear ni reducir el rol del último administrador activo';
  end if;
  new.email := old.email; new.created_at := old.created_at; new.updated_at := clock_timestamp();
  insert into public.audit_logs(user_id, action, entity, entity_id, old_data, new_data)
  values(auth.uid(), 'UPDATE', 'profiles', new.id::text, to_jsonb(old), to_jsonb(new));
  return new;
end $$;
drop trigger if exists trg_profile_update on public.profiles;
create trigger trg_profile_update before update on public.profiles for each row execute function public.guard_profile_update();

alter table public."Aliados" enable row level security;
alter table public.profiles enable row level security;
alter table public.audit_logs enable row level security;
alter table public.alert_log enable row level security;
-- Replace legacy permissive policies; their presence would bypass the new role checks.
do $$ declare policy_record record; begin
  for policy_record in select tablename, policyname from pg_policies
    where schemaname = 'public' and tablename in ('Aliados','profiles','audit_logs','alert_log') loop
    execute format('drop policy %I on public.%I', policy_record.policyname, policy_record.tablename);
  end loop;
end $$;
create policy crm_profile_read on public.profiles for select to authenticated
  using(id = auth.uid() or public.my_role() = 'administrador');
create policy crm_profile_update on public.profiles for update to authenticated
  using(public.my_role() = 'administrador') with check(public.my_role() = 'administrador');
create policy crm_agreement_read on public."Aliados" for select to authenticated
  using(public.my_role() is not null);
create policy crm_agreement_insert on public."Aliados" for insert to authenticated
  with check(public.my_role() in ('administrador','comercial'));
create policy crm_agreement_update on public."Aliados" for update to authenticated
  using(public.my_role() = 'administrador' or (public.my_role() = 'comercial' and archived_at is null))
  with check(public.my_role() = 'administrador' or (public.my_role() = 'comercial' and archived_at is null));
create policy crm_audit_read on public.audit_logs for select to authenticated using(public.my_role() = 'administrador');
create policy crm_alert_read on public.alert_log for select to authenticated using(public.my_role() = 'administrador');
revoke all on public."Aliados", public.profiles, public.audit_logs, public.alert_log from anon, authenticated;
grant select, insert, update on public."Aliados" to authenticated;
grant select, update on public.profiles to authenticated;
grant select on public.audit_logs, public.alert_log to authenticated;
grant all on public."Aliados", public.profiles, public.audit_logs, public.alert_log to service_role;
-- Grant only the agreement sequence required to create records.
do $$ declare seq_name text; begin
  seq_name := pg_get_serial_sequence('public."Aliados"', 'Id');
  if seq_name is not null then execute format('grant usage, select on sequence %s to authenticated, service_role', seq_name); end if;
end $$;
grant usage, select on sequence public.alert_log_id_seq, public.audit_logs_id_seq to service_role;
revoke all on function public.my_role() from public, anon;
grant execute on function public.my_role() to authenticated, service_role;
revoke all on function public.handle_new_user(), public.audit_aliados(), public.guard_profile_update() from public, anon, authenticated;

-- Atomic queue claim. A stale claim is retried with the same provider idempotency key.
create or replace function public.claim_crm_alert(p_key text, p_agreement bigint, p_type text, p_date date,
  p_days integer, p_slot text, p_recipient text, p_payload jsonb)
returns jsonb language plpgsql security definer set search_path = public
as $$ declare entry public.alert_log%rowtype; begin
  insert into public.alert_log(alert_key, agreement_id, alert_type, scheduled_for, days_before, run_slot, recipient, payload, status)
  values(p_key, p_agreement, p_type, p_date, p_days, p_slot, p_recipient, p_payload, 'pending') on conflict(alert_key) do nothing;
  select * into entry from public.alert_log where alert_key = p_key for update;
  if entry.status = 'processing' and entry.payload->>'provider' = 'emailjs'
     and entry.claimed_at <= now() - interval '10 minutes' then
    update public.alert_log set status='uncertain', last_error='Envío sin confirmación; revisar el proveedor antes de reintentar', updated_at=now() where id=entry.id;
    return null;
  end if;
  if entry.status in ('sent','cancelled','expired','uncertain') or entry.attempts >= 12 or
     (entry.status = 'processing' and entry.claimed_at > now() - interval '10 minutes') then return null; end if;
  update public.alert_log set status = 'processing', attempts = attempts + 1, claimed_at = now(), updated_at = now()
  where id = entry.id returning * into entry;
  return to_jsonb(entry);
end $$;
revoke all on function public.claim_crm_alert(text,bigint,text,date,integer,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.claim_crm_alert(text,bigint,text,date,integer,text,text,jsonb) to service_role;
-- Vault is the same source used by pg_cron. Only the trusted function server
-- may read this one-way digest; no secret is returned to application users.
create or replace function public.crm_cron_secret_digest()
returns text language plpgsql security definer set search_path = ''
as $$ declare result text; begin
  if pg_catalog.to_regclass('vault.decrypted_secrets') is null then return null; end if;
  execute 'select pg_catalog.encode(pg_catalog.sha256(pg_catalog.convert_to(decrypted_secret,''UTF8'')),''hex'') from vault.decrypted_secrets where name=''oralhome_cron_secret'' limit 1' into result;
  return result;
end $$;
revoke all on function public.crm_cron_secret_digest() from public, anon, authenticated;
grant execute on function public.crm_cron_secret_digest() to service_role;
commit;
